name: 'financial_due_diligence'
version: '1.0.0'
config-version: 2

# This tells dbt which profile template to use to find our credentials
profile: 'due_diligence_profile'

# This tells dbt where our SQL files live
model-paths: ["models"]
seed-paths: ["data/seeds"]

# This tells dbt how to compile our queries in DuckDB
models:
  financial_due_diligence:
    staging:
      +materialized: view  # Staging models are built as lightweight, fast Views
    marts:
      +materialized: table # Marts are built as concrete Tables for fast BI dashboard loading